copy "..\..\wxPlugin_DLL\wxPlugin - Release\*.dll"
copy "..\..\USBDM_DLL_V4\USBDM DLL Debug\*.dll"
copy "..\..\USBDM_DLL_V4\USBDM DLL Release\*.dll"
copy "..\..\USBDM_DSC_DLL\DSC_DLL - Debug\*.dll"
copy "..\..\USBDM_DSC_DLL\DSC_DLL - Release\*.dll"
copy "..\..\USBDM_ARM_DLL\ARM_DLL - Debug\*.dll"
copy "..\..\USBDM_ARM_DLL\ARM_DLL - Release\*.dll"
copy "..\..\UsbdmTcl\UsbdmTcl - Debug\*.dll"
copy "..\..\UsbdmTcl\UsbdmTcl - Release\*.dll"
copy "..\..\USBDM_JNI_DLL\Release\*.dll"
pause