/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_usbdm_connections_usbdm_Usbdm_BdmInformation */

#ifndef _Included_net_sourceforge_usbdm_connections_usbdm_Usbdm_BdmInformation
#define _Included_net_sourceforge_usbdm_connections_usbdm_Usbdm_BdmInformation
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
