/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Usbdm_BdmInformation */

#ifndef _Included_Usbdm_BdmInformation
#define _Included_Usbdm_BdmInformation
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
